services:
  eng-center-db:
    image: postgres:17.5-alpine
    container_name: eng-center-db
    restart: none
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: eng-center
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - eng-center:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: duongtheduy
      MINIO_ROOT_PASSWORD: password123
    command: server --console-address ":9001" /data
  eng-center:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: duongduyy/eng-center-app:lastest
    environment:
      - DATABASE_HOST=eng-center-db
    expose:
      - 8080
    ports:
      - 8080:8080
volumes:
  eng-center: