services:
  eng-center-db:
    image: postgres:17.5-alpine
    container_name: eng-center-db
    restart: none
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: eng-center
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - eng-center:/var/lib/postgresql/data

  eng-center:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: duongduyy/eng-center-app:lastest
    environment:
      - DATABASE_HOST=eng-center-db
    expose:
      - 8080
    ports:
      - 8080:8080
volumes:
  eng-center: